{% set name = "sracha" %}
<<<<<<< HEAD
{% set version = "0.3.1" %}
=======
{% set version = "0.3.5" %}
>>>>>>> upstream/master

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/rnabioco/sracha-rs/archive/v{{ version }}.tar.gz
<<<<<<< HEAD
  sha256: 4fd3e991bbbd6f6599dc8bce6813881b0cc5fae0ecbe0a7c1d77963ce4536f22
=======
  sha256: 7ec6b27acc416119c08959cc8cba539baee08b8979fd2800dfafacd4d6db3355
>>>>>>> upstream/master

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sracha', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - sracha --help

about:
  home: https://github.com/rnabioco/sracha-rs
  license: MIT
  license_file: LICENSE
  summary: Fast parallel SRA downloader and streaming FASTQ converter.
  dev_url: https://github.com/rnabioco/sracha-rs
  doc_url: https://github.com/rnabioco/sracha-rs#readme

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  skip-lints:
    - compiler_needs_stdlib_c
  recipe-maintainers:
    - jayhesselberth
